name: Feature Branch CD

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4.1.7
      - uses: actions/setup-java@v4.2.1
        with:
          java-version: 21
          distribution: temurin
      - run: mvn test --file pom.xml
      - uses: actions/upload-artefact@v4
        with:
          name: deploy_snapshot
          path: target/*.jar